### ISSUE TITLE
mission/vision statement, and tagline

### ISSUE THREAD

**Issue by mpryor** [notree-md/notree#41]
- We should come up with a clear and concise mission/vision statement for notree 
- We should also come up with a catchy tagline
- Once we've landed on a mission/vision/tagline we are happy with we should update the README with each, and consider how a landing paging for the notree product would look 
- We should be cognizant of the different goals of the SaaS product vs the goals of the Opensource offering(s)

**Comment by jollyjerr** [comment]
This is kinda vague, but what I'm thinking in terms of Saas/open-source is like "all the lego blocks are open source but the assembled product is closed". Strictly web concerns can just live in the product (like auth, SEO, etc) but all the actual features are open source and imported in.

I'll think on a mission statement and vision today. The specific problems I want to solve are something like "x% of everything you learn in life is forgotten or rendered irrelevant because it's not connected to other things." and also "I know concept B and want to know concept Y. My teammate knows concept Y. What is the shortest path to understanding Y if I have access to both of our docs."

**Comment by jollyjerr** [comment]
Been thinking more on this - I want notree to be focused on sharing knowledge I think. I was watching the competitive programmer [Colin Galen](https://youtu.be/Dm68uFy6gus) on youtube and they talked about like "you should never be afraid to share any little insight you have because even if it's out there already a thousand times your perspective on it might be the thing that helps someone". Also [this speech](https://youtu.be/z7GVHB2wiyg) by 3blue1brown on "Math and Ego" talks about the power of meeting someone else where they are at before you blast into some advanced concept.

All that being said, something like:

Mission: To connect people and grow knowledge together (or something lol I suck at this stuff)
Tagline: Knowledge Connects

**Comment by mpryor** [comment]
I love 3blue1brown, and thanks for the Colin Galen rec, I have not look watched their stuff before!

I think we're pretty much on the same page as far as mission/tagline goes. I want to throw some ideas out as well:

Mission statement ideas:
1. To be the platform that connects your ideas, and helps you discover connections with others. 
1. To revolutionize the way that ideas are collected, connected, and created. 
1. To provide insights and connections to your ideas that otherwise would be left undiscovered

Tagline ideas:
1. Explore a world of connected thought
1. Connect, discover, create
1. Your second brain... and everyone else's too
1. Change the way you think
1. Knowledge sharing, on a global level

**Comment by jollyjerr** [comment]
Stuff from meeting today:

## Personas

1. Techy people that understand programming and want an easy way to publish stuff (obsidian publish)
2. WordPress Bloggers (fully customizable and editable obsidian publish)
3. Technical teams that use Jira and Confluence and stuff (smaller company knowledge sharing) (this will involve custom RBAC in template systems) 
4. "The noteverse" users knowledge bases can link together and guide learning. (3d view and/or clusters view)

**Comment by jollyjerr** [comment]
I like `Notree is the platform that connects your ideas, and helps you discover connections with others.` perhaps rewritten as `Connect your ideas and discover connections with others`. And also `Notree unveils insights and connections between ideas and people` perhaps rewritten as `Discover connections between ideas and people`.

Typically I think of mission statements as a very basic "this is what we are trying to do" and not phrased like an advertisement really. Like Tesla `To accelerate the world’s transition to renewable energy.` or Microsoft `Empower every person and organization on the planet to achieve more.`

Working with the ideas we have here, how do you feel about:

Mission Statement: Spark new ideas by connecting people and their knowledge

Conversely I think the tagline should be an advertisement, like Atlassian `Impossible alone. Possible together` or TypeScript `JavaScript that scales`

Working with the ideas we have here, how do you feel about:

Tagline: Think together

**Comment by mpryor** [comment]
Okay, let's do it!

**Mission statement**: Spark new ideas by connecting people and their knowledge
**Tagline**: Share your knowledge

**Comment by jollyjerr** [comment]
![](https://media.giphy.com/media/Piu2GgbPwfjQfNTsUd/giphy.gif)
